# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoancountInf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Loancount(object):
    def setupUi(self, Loancount):
        Loancount.setObjectName("Loancount")
        Loancount.resize(839, 370)
        font = QtGui.QFont()
        font.setPointSize(12)
        Loancount.setFont(font)
        self.table = QtWidgets.QTableWidget(Loancount)
        self.table.setGeometry(QtCore.QRect(430, 10, 391, 331))
        self.table.setMinimumSize(QtCore.QSize(0, 300))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.pushButton_che = QtWidgets.QPushButton(Loancount)
        self.pushButton_che.setGeometry(QtCore.QRect(90, 210, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_che.setFont(font)
        self.pushButton_che.setObjectName("pushButton_che")
        self.label_2 = QtWidgets.QLabel(Loancount)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Loancount)
        self.label.setGeometry(QtCore.QRect(20, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_to = QtWidgets.QLabel(Loancount)
        self.label_to.setGeometry(QtCore.QRect(250, 120, 21, 16))
        self.label_to.setObjectName("label_to")
        self.dateEdit_2 = QtWidgets.QDateEdit(Loancount)
        self.dateEdit_2.setGeometry(QtCore.QRect(290, 120, 110, 22))
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_1 = QtWidgets.QDateEdit(Loancount)
        self.dateEdit_1.setGeometry(QtCore.QRect(120, 120, 110, 22))
        self.dateEdit_1.setDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_1.setObjectName("dateEdit_1")

        self.retranslateUi(Loancount)
        QtCore.QMetaObject.connectSlotsByName(Loancount)

    def retranslateUi(self, Loancount):
        _translate = QtCore.QCoreApplication.translate
        Loancount.setWindowTitle(_translate("Loancount", "Loancount"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Loancount", "分行名称"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Loancount", "业务总金额"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Loancount", "用户数"))
        self.pushButton_che.setText(_translate("Loancount", "查询"))
        self.label_2.setText(_translate("Loancount", "贷款类业务统计"))
        self.label.setText(_translate("Loancount", "时间粒度："))
        self.label_to.setText(_translate("Loancount", "to"))
